<?php
define('DEBUG_ENVIRONMENT',TRUE);
define('APPLICATION_WEB_PROTOCOL', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']) ?  'https' : 'http');
define('APPLICATION_WEB_PATH',APPLICATION_WEB_PROTOCOL.'://'.$_SERVER["SERVER_NAME"].':8080/p2/');
define('APPLICATION_VIEW_PATH',APPLICATION_PATH.'/views/');
define('APPLICATION_PUBLIC_PATH',APPLICATION_PATH.'/public/');
define('APPLICATION_PUBLIC_WEB_PATH',APPLICATION_WEB_PATH.'/public/');
define('DEBUG_IP','5.2.186.9');
